- name: Disable firewalld
  ansible.builtin.include_role:
    name: common
    tasks_from: firewalld

- name: Install Redis
  ansible.builtin.dnf:
    name: "{{ redis_package }}"
    state: present

- name: Update Redis listen address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify: restart redis
  ignore_errors: true

- name: Update Redis listen address (RHEL alternative path)
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify: restart redis
  ignore_errors: true

- name: Enable Redis service
  ansible.builtin.service:
    name: "{{ redis_service }}"
    enabled: true
    state: started