- name: Disable firewalld
  ansible.builtin.include_role:
    name: common
    tasks_from: firewalld

- name: Setup application directories
  ansible.builtin.include_role:
    name: common
    tasks_from: app-setup

- name: Install Java runtime
  ansible.builtin.include_role:
    name: common
    tasks_from: java-setup

- name: Install Maven and build package
  ansible.builtin.include_role:
    name: common
    tasks_from: maven-setup

- name: Configure systemd service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd-setup