- name: Disable firewalld
  ansible.builtin.include_role:
    name: common
    tasks_from: firewalld

- name: Copy RabbitMQ repository file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
    mode: '0644'

- name: Clean DNF cache
  ansible.builtin.command:
    cmd: dnf clean all

- name: install rabbitmq-server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Enable RabbitMQ service
  ansible.builtin.service:
    name: "{{ rabbitmq_service }}"
    enabled: true
    state: started

- name: Create RabbitMQ application user
  community.rabbitmq.rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_password }}"
    permissions:
      - vhost: /
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
    state: present