pipeline {

    agent any

    environment {

        ANSIBLE_HOST_KEY_CHECKING = "False"

        ANSIBLE_CONFIG = "${WORKSPACE}/ansible.cfg"

        PACKER_LOG = "1"
    }

    stages {

        stage('Checkout Code') {

            steps {

                git branch: 'main',
                url: 'https://github.com/Sameer-Sarrainodu/ecommerce-ansible.git'
            }
        }

        stage('Verify Ansible') {

            steps {

                sh 'ansible --version'
            }
        }

        stage('Deploy DB and Middleware') {

            steps {

                sh '''
                    ansible-playbook \
                      -i inventories/dev/hosts.ini \
                      playbooks/site.yml
                '''
            }
        }

        // stage('Packer Init') {

        //     steps {

        //         dir('packer') {

        //             sh 'packer init .'
        //         }
        //     }
        // }

        // stage('Build Service Images') {

        //     steps {

        //         dir('packer') {

        //             sh '''

        //                 set -euxo pipefail

        //                 ls -l

        //                 /usr/bin/packer init .

        //                 # /usr/bin/packer build -force \
        //                 # -only=azure-arm.catalogue \
        //                 # -var-file=variables.pkrvars.hcl \
        //                 # .

        //                 # /usr/bin/packer build -force \
        //                 # -only=azure-arm.user \
        //                 # -var-file=variables.pkrvars.hcl \
        //                 # .

        //                 # /usr/bin/packer build -force \
        //                 # -only=azure-arm.cart \
        //                 # -var-file=variables.pkrvars.hcl \
        //                 # .

        //                 # /usr/bin/packer build -force \
        //                 # -only=azure-arm.shipping \
        //                 # -var-file=variables.pkrvars.hcl \
        //                 # .

        //                 # /usr/bin/packer build -force \
        //                 # -only=azure-arm.payment \
        //                 # -var-file=variables.pkrvars.hcl \
        //                 # .

        //                 # /usr/bin/packer build -force \
        //                 # -only=azure-arm.dispatch \
        //                 # -var-file=variables.pkrvars.hcl \
        //                 # .

        //                  # /usr/bin/packer build -force \
        //                  # -only=azure-arm.frontend \
        //                  # -var-file=variables.pkrvars.hcl \
        //                 # .
        //             '''
        //         }
        //     }
        // }
        // stage('Post Deploy Configuration') {

        //     steps {

        //         sh '''
        //             ansible-playbook \
        //             -i inventories/dev/hosts.ini \
        //             playbooks/post-deploy.yml
        //         '''
        //     }
        // }

    }

    post {

        success {

            echo '✅ All service images built successfully!'
        }

        failure {

            echo '❌ Pipeline failed!'
        }
    }
}