- name: Disable firewalld
  ansible.builtin.include_role:
    name: common
    tasks_from: firewalld

- name: Install MySQL server
  ansible.builtin.dnf:
    name: "{{ mysql_package }}"
    state: present

- name: Enable MySQL service
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    enabled: true
    state: started

- name: Install PyMySQL
  ansible.builtin.dnf:
    name: python3-PyMySQL
    state: present

- name: Set MySQL root password
  ansible.builtin.shell: |
    mysql <<EOF
    ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';
    FLUSH PRIVILEGES;
    EOF
  register: mysql_password_reset
  failed_when: false
  changed_when: false

- name: Allow remote MySQL connections
  ansible.builtin.lineinfile:
    path: "{{ mysql_config_file }}"
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: restart mysql

- name: Restart MySQL after bind-address change
  ansible.builtin.meta: flush_handlers

- name: Create remote root MySQL user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: root
    host: "%"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present