- name: Install MySQL server
  ansible.builtin.dnf:
    name: "{{ mysql_package }}"
    state: present

- name: Enable MySQL service
  ansible.builtin.service:
    name: "{{ mysql_service }}"
    enabled: true
    state: started

- name: Install PyMySQL
  ansible.builtin.dnf:
    name: python3-PyMySQL
    state: present

- name: setp root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ mysql_root_password }}

- name: Allow remote MySQL connections
  ansible.builtin.replace:
    path: "{{ mysql_config_file }}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify: restart mysql
  ignore_errors: true