- name: Disable firewalld
  ansible.builtin.include_role:
    name: common
    tasks_from: firewalld

- name: Setup application directories
  ansible.builtin.include_role:
    name: common
    tasks_from: app-setup

- name: Install Golang runtime
  ansible.builtin.include_role:
    name: common
    tasks_from: golang-setup

- name: Configure systemd service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd-setup