- name: Install MongoDB repository
  ansible.builtin.copy:
    src:  "{{ playbook_dir }}/../roles/catalogue/files/mongo.repo"
    dest: /etc/yum.repos.d/mongo.repo
    mode: '0644'

- name: Install MongoDB shell client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: Check if catalogue schema already loaded
  ansible.builtin.command:
    cmd: >
      mongosh --host mongodb.roboshop.internal
      --quiet
      --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: mongo_schema_check
  changed_when: false

- name: Load catalogue schema
  ansible.builtin.shell: >
    mongosh --host mongodb.roboshop.internal
    < {{ app_home }}/db/master-data.js
  when:
    - mongo_schema_check.stdout | int < 0

- name: Restart catalogue
  ansible.builtin.systemd:
    name: catalogue
    state: restarted