pipeline {

    agent any

    environment {

        ANSIBLE_HOST_KEY_CHECKING = "False"

        ANSIBLE_CONFIG = "${WORKSPACE}/ansible.cfg"

        PACKER_LOG = "1"
    }

    stages {

        stage('Checkout Code') {

            steps {

                git branch: 'main',
                url: 'https://github.com/Sameer-Sarrainodu/ecommerce-ansible.git'
            }
        }

        stage('Verify Ansible') {

            steps {

                sh 'ansible --version'
            }
        }

        stage('Deploy DB and Middleware') {

            steps {

                sh '''
                    ansible-playbook \
                      -i inventories/dev/hosts.ini \
                      playbooks/site.yml
                '''
            }
        }

        stage('Packer Init') {

            steps {

                dir('packer') {

                    sh 'packer init .'
                }
            }
        }

        stage('Build Service Images') {

            steps {

                dir('packer') {

                    sh '''
                        packer build -var-file=variables.pkr.hcl catalogue.pkr.hcl
                        packer build -var-file=variables.pkr.hcl user.pkr.hcl
                        packer build -var-file=variables.pkr.hcl cart.pkr.hcl
                        packer build -var-file=variables.pkr.hcl shipping.pkr.hcl
                        packer build -var-file=variables.pkr.hcl payment.pkr.hcl
                        packer build -var-file=variables.pkr.hcl dispatch.pkr.hcl
                        packer build -var-file=variables.pkr.hcl frontend.pkr.hcl
                    '''
                }
            }
        }
    }

    post {

        success {

            echo '✅ All service images built successfully!'
        }

        failure {

            echo '❌ Pipeline failed!'
        }
    }
}